title: John Doe
baseline: Programmer
baseurl: http://localhost:8000/
description: John Doe, Full Stack Developer Expert Ninja.
author:
    name: Arnaud Ligny
    url: https://ligny.fr

theme:
  - resume
