title: John Doe
baseline: Programmer
baseurl: https://cecilapp.github.io/resume-demo/
description: John Doe, Full Stack Developer Ninja Expert.
author:
    name: Arnaud Ligny
    url: https://ligny.fr

theme:
  - resume
